### ISSUE TITLE
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1'

### ISSUE THREAD

**Issue by t3mp-0xCC** [t3mp-0xCC/rust-prac#1]
```
RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/prime_factorization_game`
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/main.rs:34:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.57.0/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/1.57.0/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_bounds_check
             at /rustc/1.57.0/library/core/src/panicking.rs:76:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/1.57.0/library/core/src/slice/index.rs:190:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/1.57.0/library/core/src/slice/index.rs:26:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/1.57.0/library/alloc/src/vec/mod.rs:2508:9
   6: prime_factorization_game::is_prime
             at ./src/main.rs:34:5
   7: prime_factorization_game::composite_num_gen
             at ./src/main.rs:51:11
   8: prime_factorization_game::main
             at ./src/main.rs:9:29
   9: core::ops::function::FnOnce::call_once
             at /rustc/1.57.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by t3mp-0xCC** [comment]
composite_num_genで乱数生成する時に2を使ったのがダメだった様子。

**Comment by t3mp-0xCC** [comment]
https://github.com/t3mp-0xCC/rust-prac/commit/a6901b699cdb4c06408394fb1c31f62a1b74d011

**Comment by t3mp-0xCC** [comment]
2じゃなかった、0。
眠いときに寝ないとこうなる。
